/**
 * PDF Report Generator for Pothole Intelligence System
 * Supports single and multi-image reports with embedded thumbnails
 */
function generatePDFReport() {
  const results = (typeof allAnalysisResults !== 'undefined' && allAnalysisResults.length > 0)
    ? allAnalysisResults
    : (lastAnalysisData ? [lastAnalysisData] : []);

  if (results.length === 0) { alert('No analysis data available. Run the pipeline first.'); return; }

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pw = 210, ph = 297, mx = 18, cw = pw - 2 * mx;
  let y = 0, pageNum = 1;
  const ts = new Date();

  // Colors
  const gold = [218,165,32], dark = [18,20,28], teal = [0,180,160], red = [220,60,60];
  const green = [50,180,100], muted = [120,125,145], white = [240,242,248];

  function addFooter() {
    doc.setFillColor(...dark); doc.rect(0, ph - 12, pw, 12, 'F');
    doc.setFontSize(7); doc.setTextColor(...muted);
    doc.text('Generated by Pothole Intelligence System | IIMSTC Cohort 12', mx, ph - 5);
    doc.text('Page ' + pageNum, pw - mx, ph - 5, { align: 'right' });
  }
  function newPage() { addFooter(); doc.addPage(); pageNum++; y = 20; }
  function checkPage(need) { if (y + need > ph - 20) newPage(); }

  function sectionTitle(title, icon) {
    checkPage(16);
    doc.setFillColor(...gold); doc.rect(mx, y, 3, 10, 'F');
    doc.setFontSize(11); doc.setTextColor(...dark); doc.setFont('helvetica', 'bold');
    doc.text(icon + '  ' + title, mx + 7, y + 7);
    doc.setDrawColor(200,200,200); doc.line(mx, y + 12, mx + cw, y + 12);
    y += 16;
  }
  function kv(label, value) {
    checkPage(7);
    doc.setFontSize(9); doc.setFont('helvetica','normal'); doc.setTextColor(...muted);
    doc.text(label, mx, y);
    doc.setFont('helvetica','bold'); doc.setTextColor(...dark);
    doc.text(String(value ?? '—'), mx + cw - 2, y, { align: 'right' });
    y += 6;
  }
  function tableRow(cells, isHeader) {
    const colW = cw / cells.length;
    cells.forEach((c, i) => {
      const tx = mx + i * colW + 2;
      if (isHeader) { doc.setFont('helvetica','bold'); doc.setFontSize(7.5); doc.setTextColor(...muted); }
      else { doc.setFont('helvetica','normal'); doc.setFontSize(8); doc.setTextColor(...dark); }
      doc.text(String(c ?? '—'), tx, y);
    });
    y += 5;
  }

  // ══════════════════════════════════════════════════
  //  COVER / HEADER
  // ══════════════════════════════════════════════════
  doc.setFillColor(...dark); doc.rect(0, 0, pw, 44, 'F');
  doc.setFillColor(...gold); doc.rect(0, 44, pw, 2, 'F');
  doc.setFontSize(22); doc.setTextColor(...gold); doc.setFont('helvetica','bold');
  doc.text('POTHOLE INTELLIGENCE', mx, 18);
  doc.setFontSize(11); doc.setTextColor(...white); doc.setFont('helvetica','normal');
  doc.text('Comprehensive Analysis Report', mx, 27);
  doc.setFontSize(8); doc.setTextColor(...muted);
  doc.text('Generated: ' + ts.toLocaleString(), mx, 36);
  doc.text(results.length + ' image(s) analysed', pw - mx, 36, { align: 'right' });
  y = 54;

  // ══════════════════════════════════════════════════
  //  EXECUTIVE SUMMARY (aggregate stats)
  // ══════════════════════════════════════════════════
  if (results.length > 0) {
    sectionTitle('EXECUTIVE SUMMARY', '\u25A0');
    let totalPotholes = 0, worstSev = 0, totalCost = 0, highestPriority = 0;
    results.forEach(r => {
      const d = r.predict || {};
      totalPotholes += (d.count || 0);
      worstSev = Math.max(worstSev, d.severity || 0);
      totalCost += (d.estimated_cost || 0);
      highestPriority = Math.max(highestPriority, d.priority_score || 0);
    });
    kv('Total Images Analysed', results.length);
    kv('Total Potholes Detected', totalPotholes);
    kv('Worst Severity', worstSev + ' / 5');
    kv('Highest Priority Score', highestPriority + ' / 100');
    const pLabel = highestPriority >= 70 ? 'HIGH' : highestPriority >= 40 ? 'MEDIUM' : 'LOW';
    kv('Overall Priority', pLabel + ' PRIORITY');
    kv('Total Estimated Cost', 'Rs. ' + Math.round(totalCost).toLocaleString('en-IN'));
    y += 6;
  }

  // ══════════════════════════════════════════════════
  //  PER-IMAGE SECTIONS
  // ══════════════════════════════════════════════════
  results.forEach((result, idx) => {
    const d = result.predict || {};
    const f = result.formation || {};
    const det = result.deterioration || {};
    const imgLabel = results.length > 1 ? 'IMAGE ' + (idx + 1) + ' OF ' + results.length : 'IMAGE ANALYSIS';
    const fname = result.filename || d.image?.filename || 'unknown';

    // Start each image on a new page (except first which follows exec summary)
    if (idx > 0) newPage();
    else checkPage(30);

    // ── Image header bar ──
    doc.setFillColor(235,237,242); doc.roundedRect(mx, y, cw, 10, 2, 2, 'F');
    doc.setFontSize(9); doc.setFont('helvetica','bold'); doc.setTextColor(...dark);
    doc.text(imgLabel + '  —  ' + fname, mx + 4, y + 7);
    y += 14;

    // ── Embedded thumbnail ──
    if (result.imageDataUrl) {
      try {
        checkPage(52);
        const imgW = 80, imgH = 45;
        doc.setDrawColor(180,180,180);
        doc.rect(mx, y, imgW + 2, imgH + 2);
        doc.addImage(result.imageDataUrl, 'JPEG', mx + 1, y + 1, imgW, imgH);
        // Image details beside thumbnail
        const tx = mx + imgW + 8;
        doc.setFontSize(8); doc.setFont('helvetica','normal'); doc.setTextColor(...muted);
        doc.text('Filename: ' + fname, tx, y + 6);
        doc.text('Dimensions: ' + (d.image?.width || '—') + ' x ' + (d.image?.height || '—') + ' px', tx, y + 12);
        doc.text('Source: ' + (d.source_type || 'image').toUpperCase(), tx, y + 18);
        doc.text('Inference: ' + (d.inference_time_ms || '—') + ' ms', tx, y + 24);
        doc.text('Potholes: ' + (d.count || 0), tx, y + 30);
        const sev = d.severity || 0;
        doc.text('Severity: ' + sev + '/5', tx, y + 36);
        const ps = d.priority_score || 0;
        doc.text('Priority: ' + ps + '/100', tx, y + 42);
        y += imgH + 6;
      } catch (e) { /* skip thumbnail on error */ }
    }

    // ── Detection Summary ──
    sectionTitle('DETECTION RESULTS', (idx + 1) + '.1');
    kv('Potholes Detected', d.count || 0);
    kv('Inference Time', (d.inference_time_ms || '—') + ' ms');
    const sev = d.severity || 0;
    kv('Damage Level', sev + ' / 5');
    kv('Severity Score (0-10)', d.severity_score ?? '—');

    // Severity bar
    checkPage(10);
    doc.setFillColor(230,230,230); doc.roundedRect(mx, y, cw, 5, 2, 2, 'F');
    const sevPct = Math.min(sev / 5, 1);
    const sevColor = sev <= 2 ? green : sev <= 3 ? gold : red;
    doc.setFillColor(...sevColor); doc.roundedRect(mx, y, Math.max(cw * sevPct, 1), 5, 2, 2, 'F');
    y += 8;

    const ps = d.priority_score || 0;
    const pLabel = ps >= 70 ? 'HIGH PRIORITY' : ps >= 40 ? 'MEDIUM PRIORITY' : 'LOW PRIORITY';
    kv('Priority Score', ps + ' / 100  (' + pLabel + ')');
    kv('Repair Type', d.repair_type || '—');
    kv('Estimated Cost', d.estimated_cost ? 'Rs. ' + Number(d.estimated_cost).toLocaleString('en-IN') : '—');
    if (d.repair_details?.cost_range) kv('Cost Range', d.repair_details.cost_range);
    y += 3;

    // ── RICE ──
    sectionTitle('RICE PRIORITIZATION', (idx + 1) + '.2');
    const ad = d.analysis_details || {};
    kv('RICE Score', d.rice_score ?? '—');
    kv('Reach', ad.estimated_reach ? ad.estimated_reach.toLocaleString('en-IN') + ' daily users' : '—');
    kv('Impact', ad.estimated_impact ?? '—');
    kv('Confidence', ad.estimated_confidence != null ? (ad.estimated_confidence * 100).toFixed(1) + '%' : '—');
    kv('Effort', (ad.estimated_effort ?? '—') + ' person-weeks');
    const sf = ad.severity_factors || {};
    if (sf.count_component != null) {
      kv('Count Factor', sf.count_component);
      kv('Confidence Factor', sf.confidence_component);
      kv('Area Factor', sf.area_component);
    }
    y += 3;

    // ── Cost Details ──
    sectionTitle('COST ESTIMATION (IRC)', (idx + 1) + '.3');
    const rd = d.repair_details || {};
    kv('Total Area', (rd.total_area_m2 || '—') + ' m2');
    kv('Total Volume', (rd.total_volume_m3 || '—') + ' m3');
    kv('Worst Severity', rd.worst_severity || '—');
    kv('IRC Basis', rd.basis || '—');
    kv('Estimated Cost', rd.estimated_cost ? 'Rs. ' + Number(rd.estimated_cost).toLocaleString('en-IN') : '—');
    kv('Cost Range', rd.cost_range || '—');
    const details = rd.pothole_details || [];
    if (details.length > 0) {
      y += 2; checkPage(14);
      doc.setFontSize(8); doc.setFont('helvetica','bold'); doc.setTextColor(...muted);
      doc.text('Per-Pothole Breakdown:', mx, y); y += 5;
      tableRow(['#','Conf.','Area(m2)','Depth(m)','Severity','Cost(Rs.)'], true);
      doc.setDrawColor(220,220,220); doc.line(mx, y - 1, mx + cw, y - 1);
      details.forEach(p => {
        checkPage(6);
        tableRow([p.pothole_id, (p.confidence*100).toFixed(0)+'%', p.area_m2, p.depth_m, p.severity, Number(p.cost_inr).toLocaleString('en-IN')], false);
      });
    }
    y += 3;

    // ── Formation Analysis ──
    sectionTitle('FORMATION FACTOR ANALYSIS', (idx + 1) + '.4');
    kv('Risk Score', (f.risk_score != null ? Number(f.risk_score).toFixed(1) : '—') + ' / 10');
    kv('Risk Level', f.risk_level || '—');
    kv('Dominant Factor', f.dominant_factor || '—');
    const ws = f.weather_snapshot || {};
    if (ws.temp_degC != null) kv('Temperature', ws.temp_degC + ' deg C');
    if (ws.humidity_pct != null) kv('Humidity', ws.humidity_pct + '%');
    if (ws.monthly_rainfall_mm != null) kv('Monthly Rainfall', ws.monthly_rainfall_mm + ' mm');
    if (ws.diurnal_range_degC != null) kv('Diurnal Range', ws.diurnal_range_degC + ' deg C');
    const rdata = f.road_data || {};
    if (rdata.road_type) kv('Road Type', rdata.road_type);
    if (rdata.road_age_years != null) kv('Road Age', rdata.road_age_years + ' years');
    const shap = f.shap_explanation || [];
    if (shap.length > 0) {
      y += 2; checkPage(10);
      doc.setFontSize(8); doc.setFont('helvetica','bold'); doc.setTextColor(...muted);
      doc.text('SHAP Feature Contributions:', mx, y); y += 5;
      tableRow(['Factor','Contribution'], true);
      doc.setDrawColor(220,220,220); doc.line(mx, y - 1, mx + cw, y - 1);
      shap.forEach(item => {
        checkPage(6);
        const val = Number(item.contribution ?? item.score ?? 0);
        doc.setFont('helvetica','normal'); doc.setFontSize(8);
        doc.setTextColor(...dark); doc.text(item.label || 'Factor', mx + 2, y);
        doc.setTextColor(val >= 0 ? teal[0] : red[0], val >= 0 ? teal[1] : red[1], val >= 0 ? teal[2] : red[2]);
        doc.text((val >= 0 ? '+' : '') + val.toFixed(3), mx + cw - 2, y, { align: 'right' });
        y += 5;
      });
    }
    y += 3;

    // ── Deterioration ──
    sectionTitle('DETERIORATION PREDICTION', (idx + 1) + '.5');
    kv('Urgency', (det.urgency_emoji || '') + ' ' + (det.urgency_label || '—'));
    kv('Days to Critical', det.days_to_critical != null ? det.days_to_critical : 'Not in 90 days');
    kv('Trajectory', det.trajectory || '—');
    kv('Worsen Probability', det.worsen_probability != null ? Math.round(det.worsen_probability * 100) + '%' : '—');
    kv('Will Worsen', det.will_worsen ? 'Yes' : 'No');
    kv('Predicted Severity (30d)', det.predicted_sev_30d ?? '—');
    kv('Predicted Severity (60d)', det.predicted_sev_60d ?? '—');
    kv('Predicted Severity (90d)', det.predicted_sev_90d ?? '—');
    if (det.priority_bonus != null) kv('Priority Bonus', det.priority_bonus);
    y += 3;

    // ── Detection Details Table ──
    const preds = d.predictions || [];
    if (preds.length > 0) {
      sectionTitle('DETECTION DETAILS', (idx + 1) + '.6');
      tableRow(['#','Label','Confidence','Width','Height','Area(m2)'], true);
      doc.setDrawColor(220,220,220); doc.line(mx, y - 1, mx + cw, y - 1);
      preds.forEach((p, i) => {
        checkPage(6);
        tableRow([i+1, p.label, (p.confidence*100).toFixed(1)+'%', p.bbox.width, p.bbox.height, p.area_sqm ?? '—'], false);
      });
    }
  });

  // ══════════════════════════════════════════════════
  //  FINAL SUMMARY BOX
  // ══════════════════════════════════════════════════
  checkPage(34);
  y += 4;
  doc.setFillColor(245,247,250); doc.roundedRect(mx, y, cw, 28, 3, 3, 'F');
  doc.setDrawColor(...gold); doc.roundedRect(mx, y, cw, 28, 3, 3, 'S');
  doc.setFontSize(10); doc.setFont('helvetica','bold'); doc.setTextColor(...dark);
  doc.text('REPORT SUMMARY', mx + 4, y + 7);
  doc.setFont('helvetica','normal'); doc.setFontSize(8); doc.setTextColor(...muted);

  let totalP = 0, worstS = 0, totalC = 0, highP = 0;
  results.forEach(r => {
    const d = r.predict || {};
    totalP += (d.count || 0); worstS = Math.max(worstS, d.severity || 0);
    totalC += (d.estimated_cost || 0); highP = Math.max(highP, d.priority_score || 0);
  });
  const pL = highP >= 70 ? 'HIGH' : highP >= 40 ? 'MEDIUM' : 'LOW';
  doc.text(results.length + ' image(s) | ' + totalP + ' pothole(s) | Worst Severity: ' + worstS + '/5 | Priority: ' + highP + '/100 (' + pL + ')', mx + 4, y + 14);
  doc.text('Total Est. Cost: Rs. ' + Math.round(totalC).toLocaleString('en-IN'), mx + 4, y + 20);
  const lastDet = results[results.length - 1]?.deterioration || {};
  doc.text('Urgency: ' + (lastDet.urgency_label || 'N/A') + ' | Days to Critical: ' + (lastDet.days_to_critical ?? 'N/A'), mx + 4, y + 26);

  addFooter();

  const fname = 'Pothole_Report_' + ts.toISOString().slice(0, 10) + '_' + ts.toTimeString().slice(0, 5).replace(':', '') + '.pdf';
  
  try {
    // Method 1: Try using doc.save() (standard jsPDF method)
    doc.save(fname);
    console.log('PDF downloaded successfully:', fname);
  } catch (err) {
    console.warn('doc.save() failed, trying fallback method:', err);
    try {
      // Method 2: Fallback - use blob approach for better browser compatibility
      const pdfBlob = doc.output('blob');
      const pdfUrl = URL.createObjectURL(pdfBlob);
      const link = document.createElement('a');
      link.href = pdfUrl;
      link.download = fname;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(pdfUrl);
      console.log('PDF downloaded via blob fallback:', fname);
    } catch (fallbackErr) {
      console.error('Both PDF download methods failed:', fallbackErr);
      alert('Error generating PDF. Check browser console for details.');
    }
  }
}
